qld-gov-au/qgds-bootstrap5

src/components/bs5/header/header.scss, src/main.scss
Adding Google Font "Fira Sans" to the Header Site Name
https://fonts.google.com/specimen/Fira+Sans?preview.text=For%20Government&query=fira+sans
=> QOLOE-54 add fira sans font to site header

src/components/bs5/inpageAlert/inpageAlert.hbs, src/components/bs5/inpageAlert/inpageAlert.scss
- Changes alert color to match qld-body-color
- Heading is now optional in hbs template to support existing in-situ alerts
=> QOLOE-9 Fix for PageAlert color and optional heading

src/components/bs5/video/video.data.json, src/components/bs5/video/video.hbs, src/components/bs5/video/video.scss, src/components/bs5/video/video.stories.js
[QOLOE-124] Display video without thumbnail and added url params on iframe API:
- Allow video to display when thumbnail attribute is empty and hiding video thumbnail. 
I have added a conditional check to only apply 'not-ready' css when thumbnail is not empty.
- Add URL Params for Youtube and Vimeo iFrame API:
-- Youtube: autoplay, controls 
-- Vimeo: autoplay, background, controls
[QOLOE-124]: https://ssq-qol.atlassian.net/browse/QOLOE-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [QOLOE-124] Display video without thumbnail and added url params on iframe API

src/components/bs5/video/video.data.json, src/components/bs5/video/video.functions.js, src/components/bs5/video/video.hbs, src/components/bs5/video/video.stories.js
[QOLOE-124] Fix video iFrame autoplay and minor adjustments:
- Fix conflicted 'autoplay' param between the one in json data and in videEmbedPlay function.
- Set the default value on video 'controls' to true so videos have controls by default. 
CMS content editor still can hide the video controls when they see fit.
- Rename 'transcript' attribute to 'transcriptAccordion' to better reflect its purpose.
[QOLOE-124]: https://ssq-qol.atlassian.net/browse/QOLOE-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [QOLOE-124] Fix video iFrame autoplay and other minor adjustments

.github/release.yml
per
https://github.com/qld-gov-au/qgds-qol-mvp/actions/runs/9247937337/job/25437500832
HTTP 422: Could not parse .github/release.yml: (<unknown>): mapping values are not allowed in this context at line 8 column 15 (https://api.github.com/repos/qld-gov-au/qgds-qol-mvp/releases)
Error: Process completed with exit code 1.
=> Correct release auto generation (spacing typo)

src/components/bs5/breadcrumbs/breadcrumb.functions.js, src/main.js
Makes sure event listener is only added when required (when breadcrumb is shortened).
=> QOLOE-12 attach event listener in shorten function

src/components/bs5/breadcrumbs/breadcrumb.functions.js, src/main.js
This is a fix for:
breadcrumb shortening function (breadcrumbShorten) is being called on a page regardless whether the component exists, which causing a javascript error on the page.
Changes:
- Added an init function for breadcrumb component 
- Added checking for breadcrumb existence before shortening breadcrumb
- Update function to accept maxLength parameter to allow dynamic breadcrumb length control, when required
- Utilise the event param on breadcrumbExpand event handler to allow more targeted element
=> [QOLOE-198] Handling js error when breadcrumb component does not exist.

.github/workflows/compile.js.yml, README.md, binary-repo/README.md, package.json
Update the readme to align with the new naming structure.
Improve instructions also.
Repo renaming is easy, for
https://semver.org/
its best to have the dependency in the package name, once we move to next major milestone we could rename and do a major point release, or create a new repo (and archive bs5) for the bs6 work and restart semver.
=> Readme update post repo name change

src/components/bs5/modal/modal.scss
The Close button on small size modal is squashed in Desktop view due to css flex auto shrink.
Setting flex-shrink to 0 so the button would not get squashed.
Bug:
Fixed:
=> [QOLOE-180]Fix Close button on small size modal in Desktop view.

src/components/bs5/tag/tag.data.json, src/components/bs5/tag/tag.hbs, src/components/bs5/tag/tag.scss, src/components/bs5/tag/tag.stories.js
[QOLOE-172] Add 'Status' tag.
* Added coloured 'status' tag with the following variations:
** Sizes: big (default) and small
** Emphasis levels: low and high
** Types: neutral, success, warning, error, information.
* Added stories in Storybook. 
* Replace "--qld" prefix on scss.
Icon support was in-progress, I removed it from this PR to get the MVP 'Status' tag merged and ready for Forgov implementation.
Based on Figma:
https://www.figma.com/design/nMmoukrjPJ8qvUiwmuj1bs/forgov.qld.gov.au?node-id=2864-78258&t=MfnFPDqu47wIqMBP-1
[QOLOE-172]: https://ssq-qol.atlassian.net/browse/QOLOE-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [QOLOE-172] Add Status tag

.binary-repo/.github/aws/README.md, .binary-repo/.github/aws/example_cloudfront.cfn.yml, .binary-repo/.github/aws/iam.cfn.yml, .binary-repo/.github/aws/setup_github_environment.sh, .binary-repo/.github/workflows/README.md, .binary-repo/.github/workflows/cdnAWSDeployment.yml, .binary-repo/.github/workflows/cdnAWSManualOrRollBack.yml, .binary-repo/.github/workflows/cdnDeploy.sh, .binary-repo/.github/workflows/getVersionDetails.sh, .binary-repo/README.md, .github/workflows/compile.js.yml, .github/workflows/release.yml
This includes the ability auto deploy to dev/test environment on develop/main push.
On a tag push, it will propergate to all environments and only to prod as version only (no latest touched).
A manual release needs to created to push "v*/v*.x.x-latest" to prod domain.
There is a rollback/manual workflow which also includes ability to purge a version. Note: A version release is the only way to update "v*/v*x.x.-latest" folders.
The https://github.com/qld-gov-au/qgds-bootstrap5-cdn repo a DR recovery repo on what should be in there based on the versions released.
=> QOLOE-125 CICD setup for CDN deployment via Release Binary Repo

src/components/bs5/searchInput/searchInput.hbs
HOTFIX:
This changes is to turn-off browser's autocomplete on Search input, by adding attribute `autocomplete="off"`.
JIRA:
https://ssq-qol.atlassian.net/browse/QOLOE-272
Screenshot:
=> [QOLOE-272]Turn off browser's autocomplete on Search input

src/components/bs5/navbar/_icons.scss, src/components/bs5/navbar/navbar.hbs, src/components/bs5/navbar/navbar.scss
The dropdown menu's width is now set to be fully responsive to browser's width, on desktop viewports.
Example on Large viewport:
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td><img width="656" alt="Before - Large breakpoint - 992px" src="https://github.com/qld-gov-au/qgds-bootstrap5/assets/8241421/ba95a803-98d2-4740-8b19-09fffd207358" border="1"></td>
<td><img width="656" alt="After - Large breakpoint - 992px" src="https://github.com/qld-gov-au/qgds-bootstrap5/assets/8241421/d3dc3fc7-0bc4-4102-9545-8cbda78258ce" border="1"></td>
</tr>
</table>
JIRA:
https://ssq-qol.atlassian.net/issues/QOLOE-268
=> [QOLOE-268] Set responsive width on header's dropdown menu.

.esbuild/plugins/qgds-plugin-copy-assets.js, esbuild.js, package.json, src/components/bs5/breadcumbsWrapper/breadcrumbsWrapper.stories.js, src/components/bs5/searchInput/search.functions.js, src/js/handlebars.helpers.js, src/js/handlebars.init.js
Copy all handlebars to components since it references handlebar partials which can't work when in assets/js.
handlebars.helpers.js still in same place during transition but handlebars are all in the components parts.
dist/components/handlebars.init.min.js is the bundled full version.
=> Clean up initilization system of partials. handlebarsHelpers and handlebarsPartials are modules that need to be called handlebarsHelpers(HandleBars)

.esbuild/plugins/qgds-plugin-clean-output-folders.js, .storybook/main.js, package.json, src/components/bs5/textbox/textInput.scss, src/components/bs5/video/video.hbs
Code changes cover the following items:
1. Video component - Hide transcript when its content is empty. 
JIRA: https://ssq-qol.atlassian.net/browse/QOLOE-313
Before
After
2. Select Input - Update label colour
JIRA: https://ssq-qol.atlassian.net/browse/QOLOE-197
3. Reverted unwanted updates on ESBuild that only apply to help with Theo's Storybook.
=> [QOLOE-134] Various UATs

src/components/bs5/searchInput/search.functions.js, src/components/bs5/searchInput/searchInput.scss
This is to fix the missing padding for 'Suggestions' and 'Services' labels and also styling the multi-line items in the search input.
=> QOLOE-294 SearchInput labels and multiline items

src/components/bs5/navbar/navbar.scss
Fix the outline is missing top border.
**Before:**
**After:**
=> [QOLOE-268] Fix outline on dropdown menu item.

src/scss/qld-type.scss
Rule on `<p>` tags was adding unintended top margin on every instance, e.g.
This removes the top margin from the first instance of a `<p>` inside a container element.
=> Remove top margin from first instance of paragraph tags in a container

src/components/bs5/breadcrumbs/breadcrumbs.scss, src/scss/qld-type.scss
| Before | After |
|:--------|:-------|
|![Screenshot 2024-06-26 at 3 41 27 pm](https://github.com/qld-gov-au/qgds-bootstrap5/assets/950889/a9d984d9-ccb6-4ed1-89d0-623241cfe7c3)|![Screenshot 2024-06-26 at 3 40 34 pm](https://github.com/qld-gov-au/qgds-bootstrap5/assets/950889/b1f92ae9-a0fd-4502-b9a2-2989bdcd6130)|
|![Screenshot 2024-06-26 at 3 41 45 pm](https://github.com/qld-gov-au/qgds-bootstrap5/assets/950889/9e5afed5-66ca-4faa-9008-3528a9e1618f)|![Screenshot 2024-06-26 at 3 40 25 pm](https://github.com/qld-gov-au/qgds-bootstrap5/assets/950889/1afedb96-656f-4e38-a4cb-386cf63581ac)|
=> Removed unnecessary visited link styles from breadcrumbs - light and dark theme

src/components/bs5/header/header.hbs, src/components/bs5/navbar/navbar.hbs
Allows HTML as the value for a CTA text/label without escaping. Useful when the label needs to be dynamic (such as 'Log in'/'My account') via edge-side include tag.
=> Allow HTML in CTA labels

src/components/bs5/card/card.hbs, src/components/bs5/card/card.scss
Changes card-text element from a `<p>` to a `<div>` so it can contain complex markup.
Also removes margin from the last child inside card-text container to avoid unintended spacing.
=> QOLOE-381 card-text fix

src/components/bs5/breadcrumbs/breadcrumbs.scss
Stops left chevron icon showing on large screens when the current page is at 2nd level of the IA (e.g. 'Home' is both first child and second last child)
=> QOLOE-200 Fix chevron icon at large screen sizes

src/components/bs5/searchInput/search.functions.js, src/components/bs5/searchInput/searchInput.hbs, src/components/bs5/searchInput/searchInput.scss
1. The search suggestion dropdown used to stay only for a second and then disappears when tabbing with keyboard. This change leaves it open till the user focus out of the search. Tha is how production behaves at the moment.
2. Make search suggestion outline full width:
Before:
After:
3. Replacing ul tag with div as there was no list item inside it.
=> QOLOE-470 Keep the search suggestions open until focus out

src/components/bs5/footer/footer.hbs, src/components/bs5/footer/footerForgov.hbs
[QOLOE-445] Accessibility: Added aria-label to improve Voice over on Close button at the Footer Feedback form.
When Close button is focused, Voice Over reads "Close, expanded, button"
Voice Over will read "**Close Feedback Form**, expanded, button".
While on JIRA ticket, the tester requested to remove `aria-expanded`, Bootstrap 5 Collapse will automatically adds aria-expanded regardless, for accessibility purposes.
Adding clearer aria-label will make the button a bit clearer for Voice Over users.
[QOLOE-445]: https://ssq-qol.atlassian.net/browse/QOLOE-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [QOLOE-445] Accessibility: aria-label on Close button at the Footer Feedback form.

src/components/bs5/header/header.hbs
It was reported that screen reader announces the chevron as ‘Graphic’ e.g. ‘link graphic’. This icons do not need to be read. Adding aria-hidden="true".
=> QOLOE-398 Stop chevron icon being read by screen readers

src/components/bs5/header/header.hbs, src/components/bs5/navbar/navbar.hbs
'Toggle navigation' was read twice by the screen reader, once when landing on the navigation bar root, another time when landing on the ul containing the navigation items. It was recommended by the a11y auditors to remove aria-labelledby.
=> QOLOE-441 Removing redundant aria-labelledby from navigation bar

src/components/bs5/header/header.hbs, src/components/bs5/navbar/navbar.functions.js, src/components/bs5/navbar/navbar.hbs, src/components/bs5/navbar/navbar.scss
[QOLOE-445] Accessibility: Fix screenreader for Open and Close buttons on mobile menu
On Open button, voice over will read "Open Menu, collapsed, button".
On Close button, voice over will read "Close Menu, expanded, button".
Voice Over keeps reading Open button even though the button is not visible and navigation is showing.
The fix is to change the focus using Bootstrap Collapse event handler. 
When navigation is showing (and Close button is visible), change the focus to Close button.
This way, the Voice Over will read Close button and stop reading Open button.
[QOLOE-445]: https://ssq-qol.atlassian.net/browse/QOLOE-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [QOLOE-412] Accessibility: Fix screenreader for Open and Close buttons on mobile menu

src/components/bs5/video/video.data.json, src/components/bs5/video/video.functions.js, src/components/bs5/video/video.hbs, src/js/handlebars.helpers.js
[QOLOE-421] Accessibility: print out descriptive format for video duration
It allows voice over to read "Watch video - duration X hours Y minutes Z seconds" when the video link is focused.
Example for the above video:
- Currently, the voice over reads "Watch 151".
- Fixed version, the voice over will read **"Watch video - duration 1 minute 51 seconds".**
- Added attribute `title="Play video"` on video's play <a> link
- Added `aria-label` with description of "Watch video - duration X hours Y minutes Z seconds"
- Added a Handlebar helper to print out time duration into a string in the following formats. 
- Short format: Display the duration in simplified format of "HH:MM:SS". It is the default format.
- Omits hours when value is zero - mimicking YouTube duration display
- Long format: …
=> [QOLOE-421] Accessibility: print out descriptive format for duration

src/components/squiz-dxp/inpageAlert/main.cjs, src/components/squiz-dxp/inpageAlert/manifest.json, src/components/squiz-dxp/inpageAlert/previews/example.data.json, src/components/squiz-dxp/inpageAlert/previews/preview.html
Inpage alert component for Squiz DXP using common JS and literal string.
The component is added to Queensland Government Design System (Bootstrap 5 DEV) component set:
https://dxp.squiz.cloud/organization/ssqld-1854/component-service/component-sets/qgds-bs5-dev/
=> QOLOE-495 Inpage alert component for Squiz-DXP

src/components/bs5/searchInput/searchInput.scss
Fix: Search suggestions link button
-> This makes all links within the suggestions-category have a inline padding of 1rem
-> This will not effect current links
=> Search suggestions link btn

src/components/bs5/banner/banner.scss
fix: Inline background image style in banner component
-> The issue was that a CSS custom property was missed named
-> This is now fixed within the CSS by removing the {$prefix} part of the name, as it is generated in handlebars so the {$prefix} will is not managed
=> fix: Inline background image style in banner component

src/components/bs5/searchInput/searchInput.scss
fix: Search suggestions links have an inline padding
-> This would make sure that all link items within Search -> Suggestions have a inline padding
-> This would only ever apply if the link padding did not exist
=> fix: Search suggestions link has inline padding

src/components/bs5/navbar/navbar.functions.js
Fix: Accessibility issue of keeping the tab focus within the main nav area when the main nav is visible.
Description: On a mobile device, when the burger menu is opened the screen reader can read through the items in the menu, however after the last item e.g. ‘Log in’ toggle the read continues onto the page underneath.
Recommendation: Ensure that the screen reader focus remains in the dialog until expressly dismissed using the ‘Close’ button e.g. after the last item in the list the read loops back to the first item in the dialog.
Solution: Use the current aria-hidden="true" used within navbar.functions.js to hide the main and footer tags.
This should work the same way as the current header tag works when mobile main nav is visible.
=> Fix: QGDS 170 Accessibility Fix to keep the tab focus within the mobile main nav area when visible

src/components/bs5/navbar/navbar.hbs
Fix: QGDS For Accessibility a aria-label="Home" was added to the home link as a meaningful discription for when a screen reader encounted it.
Description: Icons e.g. ‘Home’ (house) can be coded as a link trigger but do not need visible text. When encountered using a screen reader something else will be read out e.g. URL for the link destination.
Recommendation: Add an accessible name to the link so that a meaningful name (purpose) can be announced when encountered using a screen reader. Suggest using aria-label=”Home”.
=> Fix: QGDS 168 Added a aria-label to home link for accessibility

src/components/bs5/tabs/tabs.scss
Fix: Tab layout issues after latest design review.
1] Section tabs - the left edge of content above should align to left edge of tabs and tabs content.
2] Section and Default/contained tabs - if the paragraph is the last element inside the tabs content it shouldn't have any margin/padding below it (see lobotomised owl technique - check with Steve if that's our approach)
3] Default/contained tabs - the ‘tabs-area container' div should be flush/aligned to the 'tab-content container’
=> Fix: Tabs layout changes after design review
