qld-gov-au/qgds-bootstrap5

- .storybook/main.js
- .storybook/preview.js
- package.json
Keep open and use this for central fixes to new CI/CD/Repo etc if one does not exist. 
List so far:
- Removed storybook/addon-design (storybook/main.js)
- Removed unused theme include (preview.js)
- Added postinstall for new cloned repo's that have not built yet (no dist exists to run storybook)
> WIP: Develop fixes

- src/js/plugins/qgds-plugin-copy-assets.js
On build, adds sample data to /dist/sample-data/{component}/{component}.data.json 
Sample data used via Squiz GitBridge for reference and testing.
> QOLOE-54 adds sample component data to the release repo

- src/components/bs5/alert/alert.data.json
- src/components/bs5/alert/alert.hbs
- src/components/bs5/alert/alert.stories.js
Fix adds {{variantClass}} attribute and placeholder for .success, .info, .warning, .danger
> QOLOE-9 alert add variant class

- .github/workflows/compile.js.yml
> Github actions improve experience on forks

- src/components/bs5/button/button.data.json
- src/components/bs5/button/button.hbs
- src/components/bs5/button/button.scss
- src/components/bs5/button/button.stories.js
- src/main.scss
- src/scss/qld-variables.scss
Based on: https://www.design-system.health.qld.gov.au/components/buttons
Figma: https://www.design-system.health.qld.gov.au/components/buttons
> QOLOE-13 Button

- .github/dependabot.yml
- .github/workflows/Storybook-library-update.yml
Tested here
https://github.com/duttonw/formio-qld/actions/runs/8776838231/job/24080921183
> storybook auto migrator

- src/components/bs5/navbar/navbar.functions.js
Issue caused by double merge of changes + inline resolve in web GUI
> Patch: Update navbar.functions.js

- esbuild.js
Bundling handlebars.helpers.js via esbuild script.  The compiled script is required by Squiz SSJS environment.
> QOLOE-52 Bundling handlebars.helpers.js to use in Squiz env

- src/components/bs5/globalAlert/globalAlert.data.json
- src/components/bs5/globalAlert/globalAlert.hbs
- src/components/bs5/globalAlert/globalAlert.stories.js
- src/components/bs5/tag/tag.data.json
- src/components/bs5/tag/tag.hbs
- src/components/bs5/tag/tag.stories.js
Fixing some typo before implementing the corresponding metadata fields in Squiz.
> QOLOE-23 QOLOE-24 typo

- .storybook/preview.js
- Sorts component stories alphabetically A-Z
> QOLOE-54 Added alphabetical sorting function for stories

- .github/dependabot.yml
- .github/releases.yml
- .github/workflows/compile.js.yml
- .github/workflows/githubPackage.yml
- .github/workflows/npmjsPackage.yml
- .github/workflows/release.yml
- .github/workflows/update.yml
- .gitignore
- .npmgnore
- package.json
This is the same PR that is going to develop, for github actions to work, it needs to be on the primary branch which usually is main.
This is a fully automated one click version publish of a branch you choose with a selection to do a 'patch', 'minor' or 'major' increment.
When secrets are configured, it will also deploy to npmjs.
> Cicd publish

- .storybook/preview.js
- Change the sort stories method to a more reliable OOTB sort
- Fixes issue with story subpages ordering incorrectly
> QOLOE-54 sort stories alphabetically without affecting sub-pages

- src/components/bs5/tag/tag.hbs
Typo fix in "tag" handlebars template
> Changes typo in <ui> element to <ul>

- esbuild.js
- src/js/handlebars.helpers.js
- Invokes IIFE function (handlebarsHelpers) only after Handlebars library is defined
`if(typeof(Handlebars) !== 'undefined') {
handlebarsHelpers(Handlebars);
}`
> QOLOE-54 adjust handlebars.helpers.js to invoke IIFE function

- src/components/bs5/footer/footer.data.json
- src/components/bs5/footer/footer.hbs
- src/components/bs5/footer/footerForgov.hbs
- Added some extra attributes to HBS template to support ForGov 
- Changed the example JSON data structures
> QOLOE-22 change JSON structures to be more flexible in footer

- src/components/bs5/breadcrumbs/breadcrumb.functions.js
- src/components/bs5/breadcrumbs/breadcrumbs.scss
- src/main.js
Collapses middle items of long breadcrumb lists. Adds a link to expand and show all breadcrumb items.
> QOLOE-12 Add shorten and expand functionality

- src/components/bs5/button/button.data.json
- src/components/bs5/button/button.hbs
- src/components/bs5/button/button.scss
- src/components/bs5/button/button.stories.js
[QOLOE-173] Update button component based on Design QA feedback: 
- A couple of CSS styling adjustment on the button component, such as: padding, margin, active colour, label colour, min-width, and full width on mobile.
- A new argument 'Icon Position' to determine the position of the icon placement within the button. Options are: 'leading' or 'trailing'. Default is set to 'leading'.
- A new Storybook story item to show all button variants for Default colour, just to help with troubleshooting instead of clicking around on 'variant options'.
[QOLOE-173]: https://ssq-qol.atlassian.net/browse/QOLOE-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QOLOE-173] Update button component based on Design QA feedback

- src/components/bs5/button/button.hbs
- src/components/bs5/button/button.scss
- src/components/bs5/button/button.stories.js
- Adjusted button colour as per Design QA feedback.
- Added a story to display all variants of button in dark mode for troubleshooting.
> [QOLOE-173] Adjust button as per Design QA

- src/components/bs5/tag/tag.scss
Decreasing underline offset for small tags
> QOLOE-172 Decreasing underline offset for small tags

- src/components/bs5/button/button.scss
- Adjusted the button icon on several states and modes.
- Add comment on sass file.
> [QOLOE-173] Update Button following design QA

- .storybook/main.js
- .storybook/preview.js
- package-lock.json
- package.json
- src/components/bs5/button/button.stories.js
- src/components/bs5/header/header.functions.js
**Setup a11y**
**Should (basic):**
>- show violations
>- passes
>- warnings
**Includes:**
>- .storybook/main.js changes
>- .storybook/preview.js changes
>- package.json dependencies etc.
> QOLOE-224 - Setup a11y (basic)

- src/main.scss
https://ssq-qol.atlassian.net/browse/QOLOE-227
> Pulling in Noto Sans font weight 900

- src/components/bs5/navbar/navbar.scss
Contains:
>- Fix to recent font weight change
>- Others to be added when raised
> WIP: Updates 

- src/components/bs5/sidenav/sidenav.scss
- src/components/bs5/typography/typography.scss
- src/components/bs5/typography/typography.stories.js
- src/scss/qld-type.scss
- src/scss/qld-variables.scss
QA issue: https://ssq-qol.atlassian.net/browse/QOLOE-171
> QOLOE-171 Typography New QA Branch

- src/components/bs5/video/video.scss
- Update font-weight on video navigation according to Design QA
- minor scss tidy up, such as replacing --qld- to prefix variable.
> [QOLOE-201]Update Video based on Design QA and minor scss tidy up.

- src/components/bs5/accordion/accordion.scss
> BUG: QOLOE-263 Updated CSS

- src/components/bs5/spinner/spinner.scss
> QOLOE-271 CSS Changes

- src/components/bs5/formcheck/formcheck.scss
- src/components/bs5/formcheck/stories/radio/radio.stories.js
Fixed the Radio btn stories logic
> Qoloe 267 design qa for radio buttons

- src/components/bs5/card/card.hbs
- src/components/bs5/card/card.scss
- Fixing up card feature car structure and style
- Fixing up styles of cards with arrows
- Updating title underline thickness
See the screenshots in https://ssq-qol.atlassian.net/browse/QOLOE-174
> QOLOE-174 Fixing up card feature and arrow structure and style

- src/components/bs5/button/button.hbs
- src/components/bs5/button/button.scss
- src/components/bs5/button/button.stories.js
This PR is to fix the button styling effected by typography and color variables updates.
> [QOLOE-173] Fix buttons style - Design QA

- src/components/bs5/header/header.data.json
- src/components/bs5/searchInput/search.functions.js
- src/main.js
Fix for submit scenario 
Please review
> WIP: Update

- src/components/bs5/card/card.hbs
- src/components/bs5/card/card.scss
Based on figma feature cards are only needed for multi action. So no need to address them for single action.
Also arrows only appear on card with title only.
> QOLOE-174 Reverting changes to feature card and arrow

- src/components/bs5/sidenav/sidenav.hbs
- src/components/bs5/sidenav/sidenav.scss
- Active (current) nav item shouldn't be clickable
- Nav title should be clickable and inherit hover and active states like the other items
> QOLOE-277 Updating nav title and active item in side nav

- src/components/bs5/card/card.scss
- src/components/bs5/navbar/navbar.scss
- src/components/bs5/sidenav/sidenav.scss
- src/components/bs5/typography/typography.stories.js
- src/scss/qld-type.scss
See before and after [https://ssq-qol.atlassian.net/browse/QOLOE-136](https://ssq-qol.atlassian.net/browse/QOLOE-136)
> QOLOE-136 typography fixes

- src/components/bs5/textbox/textInput.scss
- src/scss/qld-variables.scss
Minor styling changes on Select input from Design QA:
https://ssq-qol.atlassian.net/browse/QOLOE-192
> [QOLOE-192]Update select input based on design QA.

- src/components/bs5/searchInput/searchInput.stories.js
- src/main.js
This is raised by test team to make the search to work with a blank query string as well.
> QOLOE-273 Make search work with a blank query string

- src/components/bs5/tag/tag.scss
> QOLOE-305 Fixing up some hover colors for action tags

- src/components/bs5/inpagenav/inpagenav.scss
Changes:
- Styling updates based on Design QA feedback for In-Page Nav component.
- CSS variable name updates to include the project's prefix.
JIRA:
https://ssq-qol.atlassian.net/browse/QOLOE-207
> [QOLOE-207] In-page nav - Design QA

- src/components/bs5/globalAlert/globalAlert.scss
- src/components/bs5/searchInput/searchInput.scss
Ticket: https://ssq-qol.atlassian.net/browse/QOLOE-190
> QOLOE-190 Search input QA

- src/components/bs5/tag/tag.scss
Focus-within is now implemented to apply the required styles on keyboard tabbing.
> QOLOE-187 Focus within state for action tags

- .storybook/preview.js
- src/components/bs5/banner/banner.hbs
- src/components/bs5/banner/banner.scss
- src/components/bs5/breadcrumbs/breadcrumbs.scss
- [QOLOE-216] Banner design QA
- Hotfix for medium viewport width in Storybook
- Fix for breadcrumb's active item colour
[QOLOE-216]: https://ssq-qol.atlassian.net/browse/QOLOE-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QOLOE-216] Banner design QA

- src/scss/qld-print.scss
- src/scss/qld-type.scss
Ticket: https://ssq-qol.atlassian.net/browse/QOLOE-245
> QOLOE-245 UAT Print QA

- src/components/bs5/footer/_colours.scss
- src/components/bs5/footer/_measurements.scss
- src/components/bs5/footer/footer.data.json
- src/components/bs5/footer/footer.scss
Added the Footer changes for QOLOE-222
Note: I am checking the issue with -> Feedback submitted
Missing feedback submitted message (not sure if its been developed or w.i.p)
This is controlled within Form IO and was working before.
> QOLOE-222 Footer component changes

- src/components/bs5/textbox/textInput.scss
- src/scss/qld-variables.scss
Styling updates on text and textarea inputs:
- Font colour for hint text
- Input box height
https://ssq-qol.atlassian.net/browse/QOLOE-197
> [QOLOE-197] Update text and textarea inputs styling - Design QA.

- src/components/bs5/footer/footer.data.json
- src/components/bs5/footer/footer.scss
Fixed the Footer FormIO radio btn issue.
Fixed the form validations to that of the DS design.
> QOLOE-222 formIO Radio btn and validation fixs

- src/components/bs5/contentFooter/contentFooter.stories.js
- src/components/bs5/typography/typography.stories.js
- src/scss/qld-type.scss
| Before | After |
|:--------|:-------|
| ![Screenshot 2024-06-26 at 10 58 15 am](https://github.com/qld-gov-au/qgds-bootstrap5/assets/950889/c2f5cc43-b48b-4b59-bd62-c93428ecd72d)| ![Screenshot 2024-06-26 at 11 52 10 am](https://github.com/qld-gov-au/qgds-bootstrap5/assets/950889/2d4fd6e3-6dfa-433d-9c79-4021ffe72ee0) |
> QOLOE-137 fix dt fontweight

- src/components/bs5/blockquote/blockquote.scss
Add ed the blockquote Padding and Visual styling
> QOLOE-205 Updated the blockquote Visual styling and Padding

- src/components/bs5/breadcrumbs/breadcrumbs.scss
Updated the Deep Page Breadcrumbs style
> QOLOE-200 updated the deep page breadcrumb style

- .storybook/preview.js
- src/components/bs5/breadcumbsWrapper/breadcrumbsWrapper.stories.js
- src/components/bs5/contentFooter/contentFooter.stories.js
- src/components/bs5/contentFooterWrapper/contentFooterWrapper.stories.js
- src/components/bs5/contentWrapper/contentWrapper.stories.js
- src/components/bs5/fullPageWrapper/fullPage.stories.js
- src/components/bs5/mainContainerWrapper/mainContainerWrapper.stories.js
- src/components/bs5/sidenavWrapper/sidenavWrapper.stories.js
- src/css/main.scss
- src/js/QGDSComponent.js
- src/stories/integration/MainIntegration.js
- src/stories/integration/integration.stories.js
Still builds correctly in npm run build-storybook
> Storybook: correct error ./storybook/preview.js cannot be fetched. in dev mode

- src/components/bs5/banner/banner.scss
Reverts qld-gov-au/qgds-bootstrap5#532
> Revert "fix: Inline background image style in banner component"

- package-lock.json
- package.json
Fix highly vulnerable packages:
- Upgraded 'watch' package
- Replace vulnerable 'live-server' with 'http-server' package
> [QOLOE-810]Resolve highly vulnerable packages

- src/components/bs5/directionLinks/DirectionLinks.mdx
- src/components/bs5/directionLinks/directionLinks.data.json
- src/components/bs5/directionLinks/directionLinks.hbs
- src/components/bs5/directionLinks/directionLinks.js
- src/components/bs5/directionLinks/directionLinks.scss
- src/components/bs5/directionLinks/directionLinks.stories.js
- src/css/main.scss
- src/css/qld-type.scss
- src/css/qld-variables.scss
- src/js/handlebars.partials.js
Init: Direction Link. [WIP]
This is the init version and I will need to talk to the designers around:
1] Expected behaviours of the btn [i.e JS needed to go back or forward and how this is init ed]
2] Animation and if it should or should not have it [As most other btn's have it, but not sure]
I am expecting a few changes.
> QGDS-140 init: Direction Link

- src/components/bs5/globalAlert/globalAlert.data.json
- src/components/bs5/globalAlert/globalAlert.scss
- src/components/bs5/globalAlert/globalAlert.stories.js
- src/components/bs5/inpageAlert/inpageAlert.scss
- Links colour (and its underline) on Global Alert should be the same as other text colour, including "visited" state.
- Links colour (and its underline) on InPage Alert should follow link colour.
> [QGDS-152]Fix links colour on GlobalAlert

- src/components/bs5/button/button.data.json
- src/components/bs5/button/button.hbs
- src/components/bs5/button/button.scss
Fix: Added qld-icon icons and min-width of 160px to button component
> QGDS 185 Added qld-icon to button component

- src/components/bs5/inpagenav/inpagenav.scss
- Adjusts top margin on Inpage Navigation link list
> Fix: Adjust list top margin; reformat (prettier)

- src/components/bs5/searchInput/searchInput.scss
Corrected right side padding to prevent search text from touching the search button
> fixed right padding to keep space between search text and button

- src/components/bs5/accordion/Accordion.mdx
- src/components/bs5/banner/Banner.mdx
- src/components/bs5/breadcrumbs/Breadcrumbs.mdx
- src/components/bs5/callToAction/callToAction.mdx
- src/components/bs5/card/Card.mdx
- src/components/bs5/footer/Footer.mdx
- src/components/bs5/globalAlert/GlobalAlert.mdx
- src/components/bs5/inpageAlert/InpageAlert.mdx
- src/components/bs5/linkColumns/linkColumns.mdx
- src/components/bs5/promotionalPanel/PromotionalPanel.mdx
For the below components in storybook, provided a JSON documentation on the component page.
- Footer.MDX
- Accordion.MDX
- Cards.MDX
- Breadcrumbs.MDX
- Banner.MDX
- PromoPanel.MDX
- LinkColumns.MDX
- CallToAction.MDX
- InpageAlert.MDX
- GlobalAlert.MDX
> Qgds 269 bootstrap 5 add json documentation in storybook

- src/components/bs5/accordion/__snapshots__/accordion.test.js.snap
- src/components/bs5/accordion/accordion.data.json
- src/components/bs5/accordion/accordion.hbs
- src/components/bs5/accordion/accordion.scss
- src/components/bs5/accordion/accordion.stories.js
- src/components/bs5/accordion/accordion.test.js
- Adds role="region" on the collapsible panel
- Adds headingTag for flexible heading level, but fallback to H2 by default
- Non-breaking change: **accordion.data.json**, adds _headingTag_ JSON variable
- Non-breaking change: **accordion.hbs**,  adds _headingTag_ syntax with fallback to original "h2" tag
> Accessibility: Accordion Component, improve markup

- src/css/mixins/sr-only.scss
- src/css/utilities/_index.scss
- src/css/utilities/sr-only.scss
- Create .sr-only utility class using Bootstrap's visually-hidden() mixin for proper accessibility
- Add import to utilities index
> feat(accessibility): add .sr-only utility class
